[tool.poetry]
name = "toad"
version = "0.1.0"
description = ""
authors = ["Patrick Haller <patrickhaller40@googlemail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
colorama = "^0.4.4"
requests = "^2.24.0"
Pygments = "^2.7.2"
toady = "^1.70"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
example = "example:example"