# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Python Poetry Action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Install dependencies
      run: poetry install
    - name: Lint with pylint
      run: poetry run python -m pylint frosch
    - name: Test with pytest
      run: poetry run python -m pytest tests
    - name: Build and publish
      env:
        USER: ${{ secrets.PYPI_USERNAME }}
        PWD: ${{ secrets.PYPI_PASSWORD }}
      run: poetry publish --build -u "$USER" -p "$PWD"

